name: "Dependabot"

on:
  pull_request_target:

jobs:
  auto_merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    name: "Auto merge"
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.PERSONAL_REPO_TOKEN}}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '@dependabot squash and merge'
            })
